-- Character stats on users + unspent points from level-ups (baseline 1 each).
ALTER TABLE users
  ADD COLUMN stat_str TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_agi TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_vit TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_int TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_dex TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_luk TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN stat_points_unspent SMALLINT UNSIGNED NOT NULL DEFAULT 0;
