-- Daily quest catalog v2 (Swordsman dailies ids 1–7, then Archer … All-Rounder). base_exp bands: easy 10-20, medium 30-50, hard 60-100.
-- Wipes and reinserts (CASCADE clears job_task_types + user_daily_tasks for those types).
USE reborn;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM task_types;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO task_types (id, slug, name, description, alternatives, stat_tag, base_exp, sort_order) VALUES
(1, 'sn_strength_session', 'Strength session (45–60 min)', 'Structured resistance training — gym or home: compounds, machines, or dumbbell work you can repeat next week (honor system).',
 CAST('["Push/pull/legs day","Upper/lower split","Full-body heavy + accessories"]' AS JSON), 'strength', 40, 10),
(2, 'sn_pushups', 'Push-up work (~30 reps)', 'Push-up volume with solid form: about 30 reps across sets, or a short ladder — stop before form collapses.',
 CAST('["Standard + incline mix","Knee or wall if building up","Slow-tempo sets"]' AS JSON), 'strength', 15, 20),
(3, 'sn_core_plank', 'Core / plank (10+ min)', 'Plank, hollow body, dead bug, or carries — 10+ minutes total of focused core work.',
 CAST('["Front/side plank rounds","Dead bug + hollow body","Farmer carry + anti-rotation"]' AS JSON), 'endurance', 20, 30),
(4, 'sn_cold_shower', 'Cold shower finish', 'End your shower with cold water 30–90 seconds — steady breathing, one clean exposure to discomfort.',
 NULL, 'discipline', 15, 40),
(5, 'sn_run_incline_mobility', 'Run, incline walk, or mobility', 'Easy run, incline treadmill walk, OR 15–20 minutes of mobility (hips, shoulders, thoracic — quality over speed).',
 CAST('["20–30 min easy jog","10–15 min incline walk","Yoga or mobility flow"]' AS JSON), 'endurance', 18, 50),
(6, 'sn_wake_target', 'Wake on time — no snooze', 'Hit the wake time you committed to without a snooze spiral; within ~15 minutes of target still counts if honest.',
 NULL, 'discipline', 20, 60),
(7, 'sn_hardest_first', 'Hardest task before noon', 'Pick the heaviest task of your day and get it meaningfully started (or done) before noon — no excuses challenge.',
 NULL, 'discipline', 30, 70),

(8, 'arc_deep_work_60', 'Deep work (60 minutes)', 'One uninterrupted 60-minute block: one task, notifications off, no feed checks — stop the clock honestly.',
 NULL, 'precision', 30, 80),
(9, 'arc_skill_hour', 'Skill practice (1 hour)', 'Focused practice: coding, design, editing, writing, or research with notes — one continuous hour (or two 30m blocks same day).',
 CAST('["LeetCode / project code","Figma / design drill","Draft + revise writing","Source reading + notes"]' AS JSON), 'intelligence', 35, 90),
(10, 'arc_digital_clarity', 'Notifications off + clean workspace', 'Turn off non-essential notifications for your work window and reset your digital workspace (tabs, desktop, dock) to one mission.',
 NULL, 'discipline', 16, 100),
(11, 'arc_top_three_done', 'Top 3 priorities — all done', 'Write your top 3 outcomes for the day, then finish all three before you log this (no moving goalposts).',
 NULL, 'discipline', 30, 110),
(12, 'arc_pomodoro_one', 'One Pomodoro session', 'Complete one full Pomodoro (e.g. 25/5 or 50/10) on a single task without switching.',
 NULL, 'precision', 15, 120),
(13, 'arc_no_social_3h', 'No social feeds (3 hours)', 'Three consecutive hours without social or doomscroll apps (work tools OK if not feeds).',
 NULL, 'discipline', 25, 130),
(14, 'arc_pomodoro_run', 'Four Pomodoros, one target', 'Four Pomodoro cycles on the same project or skill line — build depth, not breadth.',
 NULL, 'precision', 28, 140),

(15, 'mg_read_book', 'Read (book or deep article)', 'Baca buku atau artikel panjang (self-improvement / pengetahuan)  -  20-40 menit.',
 CAST('["Physical book","E-reader","Longform web reader mode"]' AS JSON), 'intelligence', 18, 150),
(16, 'mg_watch_course', 'Course or lesson', 'Satu modul atau video edukatif (Udemy, YouTube belajar, dll.) dengan catatan singkat.',
 NULL, 'intelligence', 35, 160),
(17, 'mg_write_insight', 'Write insights', 'Tulis 5-10 bullet insight dari apa yang kamu pelajari hari ini.',
 NULL, 'intelligence', 40, 170),
(18, 'mg_learn_ai', 'Learn AI / tech', 'Pelajari satu topik AI atau teknologi (docs, tutorial, playground)  -  30+ menit.',
 NULL, 'intelligence', 40, 180),
(19, 'mg_reflect_learn', 'Reflect: what did I learn?', 'Reflect: Apa yang saya pelajari hari ini? Tulis jawaban jujur.',
 NULL, 'spirit', 15, 190),
(20, 'mg_mind_map', 'Mind map one topic', 'Buat mind map untuk satu topik yang sedang dipelajari.',
 NULL, 'intelligence', 35, 200),

(21, 'aco_meditate_10', 'Meditate (10 minutes)', 'Seated or guided meditation — 10 minutes of honest attention (timer counts; no parallel scrolling).',
 NULL, 'spirit', 20, 210),
(22, 'aco_gratitude', 'Gratitude journal', 'Write at least three specific gratitudes from today — people, moments, or small wins that were real.',
 NULL, 'spirit', 15, 220),
(23, 'aco_stretch_recover', 'Stretch, yoga, or slow walk', '15–20 minutes of gentle stretching, yoga, or a slow recovery walk — downshift your nervous system.',
 CAST('["Full-body stretch sequence","Yin or restorative yoga","Easy outdoor walk, no podcast rush"]' AS JSON), 'balance', 20, 230),
(24, 'aco_sleep_target', 'Sleep: lights-out on time', 'Start wind-down and be in bed with lights out by the time you committed to (honor system).',
 NULL, 'discipline', 20, 240),
(25, 'aco_kind_selftalk', 'No harsh self-talk day', 'When the inner critic shows up, notice it and rephrase with kindness — keep the day clean of verbal self-attack.',
 NULL, 'spirit', 25, 250),
(26, 'aco_breathe_quiet', 'Deep breathing + quiet pause', '5–10 minutes of deliberate breathing (box, 4-7-8, slow nasal) plus a few minutes stillness without new inputs.',
 NULL, 'spirit', 18, 260),
(61, 'aco_heal_connect', 'Forgive, reach out, or speak kindly', 'One honest act: forgive someone (in writing or silently), check in with family or a friend, or choose kind words in a tense moment.',
 NULL, 'spirit', 22, 265),

(27, 'rog_start_5min', 'Start within 5 minutes', 'Pick one stalled task and begin real work within 5 minutes of reading this — then continue at least 15 minutes.',
 NULL, 'agility', 15, 270),
(28, 'rog_three_quick_wins', 'Clear 3 small pending tasks', 'Finish three small tasks you have been putting off (each should be under ~20 minutes — honest completions).',
 NULL, 'discipline', 25, 280),
(29, 'rog_hiit_15', 'HIIT (15 minutes)', 'At least 15 minutes of high-intensity intervals — bike, jump rope, bodyweight Tabata, or class video.',
 CAST('["Tabata rounds","Bike sprints","Jump rope + burpee mix"]' AS JSON), 'endurance', 30, 290),
(30, 'rog_declutter_10', 'Declutter 10 minutes', '10 focused minutes clearing physical or digital clutter — desk, drawer, downloads, or one messy folder.',
 NULL, 'discipline', 15, 300),
(31, 'rog_execute_hour', 'One hour: execution only', 'One clock hour biased to doing: ship steps, send messages, build — no research rabbit holes unless the task is “look up one fact and apply it.”',
 NULL, 'precision', 25, 310),
(32, 'rog_time_attack', 'Time attack: 3 tasks', 'Complete at least three concrete tasks within 45 minutes — timer on, minimal context switching.',
 NULL, 'agility', 28, 320),
(62, 'rog_cut_noise', 'Cut feeds + simplify surface', 'Unsubscribe, mute, or remove at least two attention drains — plus simplify one workspace (tabs, inbox view, or phone home screen).',
 NULL, 'discipline', 18, 325),

(33, 'mer_product_upload', 'Upload one product or listing', 'Publish or update one sellable unit — SKU, digital file, service package, or marketplace listing with honest details.',
 NULL, 'discipline', 25, 330),
(34, 'mer_marketing_post', 'One marketing or sales post', 'One piece of content meant to sell or nurture leads: post, short video, carousel, or email blast.',
 NULL, 'discipline', 20, 340),
(35, 'mer_lead_message', 'Message one lead or prospect', 'One real outreach: DM, email, call, or follow-up to a warm or qualified lead (no spam — honest conversation).',
 NULL, 'precision', 20, 350),
(36, 'mer_finance_track_day', 'Track money for the day', 'Log today’s income and expenses in your system (app, sheet, or notebook — complete enough to trust).',
 NULL, 'discipline', 15, 360),
(37, 'mer_listing_polish', 'Improve listing or creative', 'Upgrade one conversion surface: description, thumbnail, title, pricing display, or CTA — one visible improvement shipped.',
 NULL, 'intelligence', 20, 370),
(38, 'mer_close_sale', 'Close one sale', 'Complete one paid transaction or signed agreement you were working toward (honor system — real customer, real value).',
 NULL, 'discipline', 50, 380),
(63, 'mer_offer_or_lesson', 'Offer, bundle, or marketing lesson', 'Either: draft or test one offer/bundle/pricing tweak — OR spend 25+ minutes on one structured marketing lesson (video, course module, or article + notes).',
 NULL, 'intelligence', 22, 385),

(39, 'blk_feature_small', 'Build one small feature', 'Ship one contained feature or behavior change — merged, behind a flag, or demoable locally (honest “done enough to use”).',
 NULL, 'intelligence', 35, 390),
(40, 'blk_bug_fix', 'Fix one bug', 'Resolve one real defect: reproduce, patch, verify — not just hiding the symptom.',
 NULL, 'intelligence', 20, 400),
(41, 'blk_ui_section', 'Improve one UI section', 'Polish or redesign one screen, flow slice, or component for clarity, hierarchy, or accessibility.',
 NULL, 'precision', 25, 410),
(42, 'blk_refactor_file', 'Refactor one messy file', 'Tame one tangled module: clearer structure, names, or boundaries — behavior preserved, debt reduced.',
 NULL, 'intelligence', 25, 420),
(43, 'blk_doc_note', 'Write one useful doc note', 'One piece of documentation someone else (or future you) will use: README slice, ADR, API note, or runbook step.',
 NULL, 'discipline', 15, 430),
(44, 'blk_design_or_proto', 'Design a component or prototype', 'Produce one concrete design artifact: Figma component, wire slice, or clickable prototype of an idea.',
 NULL, 'precision', 30, 440),
(64, 'blk_system_pass', 'Document, organize, or automate', 'Pick one: document a process, reorganize project/folder structure for clarity, or automate a repeated manual task (script, shortcut, or rule).',
 NULL, 'discipline', 22, 445),

(45, 'nov_wake_window', 'Wake up on time', 'Bangun dalam jendela targetmu (±30 menit dari jam yang kamu komit). Bangun konsisten = fondasi hari.',
 NULL, 'discipline', 12, 450),
(46, 'nov_water_hydrate', 'Drink enough water', 'Hidrasi jujur hari ini: ~2L air atau targetmu sendiri (botol terukur / gelas berulang).',
 CAST('["Botol 500ml ×4","Satu botol besar + isi ulang","Teh/herbal tanpa gula ikut hitung"]' AS JSON), 'vitality', 10, 460),
(47, 'nov_walk_20_30', 'Walk 20–30 minutes', 'Jalan kaki santai atau brisk 20–30 menit — outdoor, treadmill, atau mutasi yang setara.',
 CAST('["Dua blok 12–15 menit","Satu walk panjang","Jalan + tangga"]' AS JSON), 'endurance', 15, 470),
(48, 'nov_tidy_space', 'Tidy room or desk (10 min)', 'Bereskan meja atau satu zona ruangan — 10 menit fokus, bukan deep clean marathon.',
 NULL, 'discipline', 10, 480),
(49, 'nov_read_pages', 'Read 5–10 pages', 'Baca buku atau bacaan panjang (bukan doomscroll): 5–10 halaman atau ~15 menit fokus.',
 CAST('["Buku fisik","E-reader","Artikel panjang mode reader"]' AS JSON), 'intelligence', 15, 490),
(50, 'nov_one_task_focus', 'Finish one important task', 'Satu tugas penting: mulai dan selesaikan hari ini tanpa ditunda ke besok (honor system).',
 NULL, 'discipline', 20, 500),

(67, 'arnd_physical', 'Physical session', 'Satu sesi physical jelas: gym, lari, home workout, atau olahraga pilihanmu.',
 NULL, 'strength', 15, 4510),
(68, 'arnd_mental', 'Mental reset block', 'Satu blok mental: baca ringan, meditasi singkat, atau journal.',
 NULL, 'spirit', 15, 4520),
(69, 'arnd_money', 'Money touchpoint', 'Satu sentuhan uang: catat, posting jualan, invoice, atau cek pricing.',
 NULL, 'discipline', 35, 4530),
(70, 'arnd_learning', 'Structured learning block', 'Satu blok belajar terstruktur: course, bab buku, atau latihan skill.',
 NULL, 'intelligence', 15, 4540),
(74, 'arnd_steps', 'Walk toward 8k-10k steps', 'Jalan menuju 8k-10k langkah hari ini.',
 NULL, 'endurance', 15, 4550),
(75, 'arnd_four_pillars', 'Four pillars check-in', 'Centang jujur: 1 physical + 1 mental + 1 money + 1 learning  -  semua ada sentuhan hari ini.',
 NULL, 'balance', 45, 4560);

ALTER TABLE task_types AUTO_INCREMENT = 200;
